### ISSUE TITLE
Does set support updates?

### ISSUE THREAD

**Issue by francisco1844** [arriqaaq/skiplist#2]
Trying this
```
package main

import (
	"fmt"

	"github.com/arriqaaq/skiplist"
)

type kv struct{ k, v string }

func main() {
	// Set (accepts any value)
	n := skiplist.New()

	n.Set("p1", 1)
	n.Set("p2", 1)

	// Get
	node := n.Get("p1")
	fmt.Println(node.Value())
	intvar := node.Value().(int) + 1
	n.Set("p1", intvar)
	node = n.Get("p1")
	fmt.Println(node.Value())

	// Delete
	n.Delete("p1")
}

```
And get
```
1
1
```

Does that mean set operation can only create new records, but not update them?

**Comment by arriqaaq** [comment]
Skiplist is different than a set, a skip list is a probabilistic data structure. The skip list is used to store a sorted list of elements or data with a linked list. It allows the process of the elements or data to view efficiently. In one single step, it skips several elements of the entire list, which is why it is known as a skip list.

For set, this is the structure https://github.com/arriqaaq/set

**Comment by arriqaaq** [comment]
And also sorted sets use a similar skiplist, but the implementation is slightly different as it does update

https://github.com/arriqaaq/zset/blob/28b8feff17bb46018557b218d0e92dd470a8d359/zset.go#L416

**Comment by arriqaaq** [comment]
Thinking about it, I am wondering if I need to add that check here for a skiplist because as you've pointed out, a client can set multiple values of the same key but never get the latest because it is added as a new element. Lemme check it out

**Comment by arriqaaq** [comment]
Just fixed it and added a test case for it

https://github.com/arriqaaq/skiplist/blob/45b7f63cf42fbc240f4311ff442df2e7ed888654/skiplist_test.go#L80

**Comment by arriqaaq** [comment]
also addressed the update in this PR

https://github.com/arriqaaq/skiplist/pull/3

**Comment by francisco1844** [comment]
Tried with my test code. Looks good. Thanks.
